### ISSUE TITLE
EarlyStopping Missing

### ISSUE THREAD

**Issue by Andrea-Oliveri** [deephealthproject/eddl#108]
Good Afternoon,
I looked at the documentation and at the list of Deep Learning features and I did not find any callback of the fit function. I was, more specifically, looking to the EarlyStopping callback.
I was hence wondering wether you planned on releasing it in a nearby future nonetheless and, if not, how could I implement them with the current status of eddl.
Thank you in advance for your help.

**Comment by RParedesPalacios** [comment]
Yes, is missing. You can get something similar just calling fit() with epoch=1 and evaluate after each fit. You can acmes to model errors right now through fitter net attributes. Not clean, so we have to provide an API for that. Deadline to provide that: June.
