### ISSUE TITLE
Bias and Kernel regularisation and initialisation for Conv Layer

### ISSUE THREAD

**Issue by Andrea-Oliveri** [deephealthproject/eddl#110]
Good Afternoon,
I saw in the documentation that Regulisers and Initialisers are implemented under the form of separate layers and not as parameters to the Conv layer. There are however no examples showing how the weights could be regularised and initialised neither for the kernel nor for the bias of the Conv layer.
Could you please give me an example of how to implement this with the existing layers?
Thank you for your help.

**Comment by RParedesPalacios** [comment]
You actually have examples, check for instance:

https://github.com/deephealthproject/eddl/blob/master/examples/nn/1_mnist/3_mnist_mlp_regularizers.cpp

for regularizers

**Comment by Andrea-Oliveri** [comment]
Thank you very much for your answer, however I was interested in kernel and bias regulisers, and not activity regulisers (which would regularise the output of the Conv layer as shown in the exemple). I apologise for this miscomprehension. Would there be a way to apply a regulariser to the kernel and bias of the layer individually?
Once again, thank you in advance for your help

**Comment by RParedesPalacios** [comment]
Andrea, they are indeed parameter regularisers. Activation regularisers (constraints) are not implemented right now

**Comment by Andrea-Oliveri** [comment]
Thank you for having clarified that this only regularises the kernel and that bias regularisation is not implemented yet. This is not very clear from the documentation. May I please ask when is bias regularisation scheduled to be implemented?

**Comment by RParedesPalacios** [comment]
Well, normally bias doesn't use to be regularised. 

https://machinelearningmastery.com/how-to-reduce-overfitting-in-deep-learning-with-weight-regularization/

in particular when mentioned: "A separate regularizer can also be used for the bias via the bias_regularizer argument, although this is less often used."
