### ISSUE TITLE
Segfault deleting net with no call to build

### ISSUE THREAD

**Issue by simleo** [deephealthproject/eddl#112]
This program produces a segmentation fault:

```cpp
#include <eddl/apis/eddl.h>

using namespace eddl;

int main(int argc, char **argv) {
    layer in = Input({784});
    layer l = in;
    l = Activation(Dense(l, 256), "relu");
    layer out = Dense(l, 784);
    model net = Model({in}, {out});
    delete net;
}
```

The problem seems to be that the `Net` destructor assumes the presence of some attributes that are only created after a call to `build` (i.e., the constructor does not fully construct the object).

In Python the problem occurs even without the explicit deletion of `net`, since it's destroyed automatically when the interpreter exits.

**Comment by salvacarrion** [comment]
Thanks for notifying it. We'll fix it as soon as possible.

Note for the users: You can still work with either the PyEDDL (Python) or the EDDL (C++)

**Comment by salvacarrion** [comment]
Fixed
