### ISSUE TITLE
Get Loss and Metric values inside the program rather than print them on screen

### ISSUE THREAD

**Issue by Andrea-Oliveri** [deephealthproject/eddl#119]
Good Morning,
following issue #108 I was trying to implement Early Stopping myself. I, however, run into a problem when trying to get the loss of my network in order to treat it the program rather than printing it on to the screen. This code does not work:
```
Loss* l = eddl::getLoss("soft_cross_entropy");
std::cout << eddl::compute_loss(l);
```
and fails with compilation error: `cannot convert 'Loss*' to 'eddl::loss {aka NetLoss*}' for agument '1' to 'float eddl::compute_loss(eddl::loss)'`
My question would hence be if you could please provide an exemple of how to use the provided functions to obtain the losses and metric values that are printed on the screen for each batch and epoch inside of the program.
Thank you in advance for your help.

**Comment by RParedesPalacios** [comment]
Yes, it is something that I will check soon. Perhaps next week. Thanks for your suggestions, you are welcome to keep on trying EDDL and send us all these comments.

**Comment by RParedesPalacios** [comment]
Andrea i will work Omnium this issue and others along these days. Anyway you can access to the metrics and losses results through the total_loss and total_metric variables of the model. 

net->total_loss and net->total_metric

also to average by the number of samples processed you have to divide by the inferenced_samples attribute

Chekc for instance the print_loss method in Net to see what I mean:


void Net::print_loss(int b)
{
  int p = 0;

  for (int k = 0; k < lout.size(); k++, p += 2) {
      total_loss[k] += fiterr[p];  // loss
      total_metric[k] += fiterr[p + 1];  // metric
      fiterr[p] = fiterr[p + 1] = 0.0;
      fprintf(stdout,"Batch %d ",b);
      fprintf(stdout, "%s(%s=%1.3f,%s=%1.3f) ", lout[k]->name.c_str(),
              losses[k]->name.c_str(), total_loss[k] / inferenced_samples,
              metrics[k]->name.c_str(), total_metric[k] / inferenced_samples);

      if ((flog_tr!=nullptr)&&(trmode))
        fprintf(flog_tr, "%s %1.3f %s %1.3f ", losses[k]->name.c_str(), total_loss[k] / inferenced_samples,
                metrics[k]->name.c_str(), total_metric[k] / inferenced_samples);

      if ((flog_ts!=nullptr)&&(!trmode))
        fprintf(flog_ts, "%s %1.3f %s %1.3f ", losses[k]->name.c_str(), total_loss[k] / inferenced_samples,
                metrics[k]->name.c_str(), total_metric[k] / inferenced_samples);

  }
....

**Comment by salvacarrion** [comment]
Fixed. #219
