### ISSUE TITLE
Unable to load mnist ONNX model

### ISSUE THREAD

**Issue by olivierbichler-cea** [deephealthproject/eddl#132]
Hi,

I tried to load the mnist ONNX model from:
https://github.com/onnx/models/tree/master/vision/classification/mnist

with the `onnx_import` example and I get a segmentation fault:

> 
> Ir_version < 6
> Producer_name: CNTK
> Producer_version: 2.4
> Domain: 
> Model_version: 1
> Segmentation fault (core dumped)

**Comment by RParedesPalacios** [comment]
thanks for the issue we will see...

**Comment by Seraphid** [comment]
There was a bug within the transmute operation, but it is already fixed and the new release will be able to load your net. I have already done it in the develop branch.
`Ir_version < 6
Warning: Version is inferior to the one supported. ONNX module will try to load it anyway
Ir_version = 3
Operator domain  = 
Operator version = 8
Producer_name: CNTK
Producer_version: 2.5.1
Domain: ai.cntk
Model_version: 1
Net imported from ONNX succesfully
Generating Random Table
Output size list = 1
CS with low memory setup
Selecting GPU device 0
EDDLL is running on GPU device 0, GeForce GTX 1080
CuBlas initialized on GPU device 0, GeForce GTX 1080
CuRand initialized on GPU device 0, GeForce GTX 1080
---------------------------------------------
Input3                        |  (1, 28, 28)=>      (1, 28, 28)
Convolution28                 |  (1, 28, 28)=>      (8, 28, 28)
ReLU32                        |  (8, 28, 28)=>      (8, 28, 28)
Pooling66                     |  (8, 28, 28)=>      (8, 14, 14)
Convolution110                |  (8, 14, 14)=>      (16, 14, 14)
ReLU114                       |  (16, 14, 14)=>      (16, 14, 14)
Pooling160                    |  (16, 14, 14)=>      (16, 4, 4)
Times212_reshape0             |  (16, 4, 4)=>      (256)     
Times212                      |  (256)     =>      (10)      
---------------------------------------------
`
I'll close this thread now, open another issue if after the release this net can't be imported.
