### ISSUE TITLE
Error when importing onnx networks from keras/tensorflow

### ISSUE THREAD

**Issue by fversaci** [deephealthproject/eddl#143]
Hi, I'm trying to import an onnx network from tensorflow/keras to eddl (0.4.4) and I'm getting a core dump, both using tf1 or tf2. I attach the code for creating minimal onnx networks (tf1.py and tf2.py) and trying to read them (read-error.py) causing the core dump. Thanks!
[onnx-read-error.zip](https://github.com/deephealthproject/eddl/files/4487614/onnx-read-error.zip)

**Comment by Seraphid** [comment]
Hi,

we will try to reproduce this bug and fix it as soon as posible. I will reply again when we learn something about it.
