### ISSUE TITLE
regex_error when loading npy

### ISSUE THREAD

**Issue by Andrea-Oliveri** [deephealthproject/eddl#147]
Good Morning,
in the latest version of eddl (this issue was not present in old versions), when trying to read a tensor from a .npy file with `Tensor* a = Tensor::load<double>("file.npy");` the program quits throwing a std::regex_error. Note that the .npy file was generated with `np.save("file.npy", a)`

**Comment by salvacarrion** [comment]
We're considering dropping the support for non-native files (numpy, csv, tsv,...) since we're using third-party libraries that not well-tested, and those files can be easily read using Python.
