### ISSUE TITLE
Missing Dice Loss and Focal Loss

### ISSUE THREAD

**Issue by CostantinoGrana** [deephealthproject/eddl#153]
In order to work with the pneumothorax challenge, the evaluation is given with the [Dice coefficient](https://en.wikipedia.org/wiki/S%C3%B8rensen%E2%80%93Dice_coefficient): https://www.kaggle.com/c/siim-acr-pneumothorax-segmentation/overview/evaluation
It would be important to have [Dice loss](https://lars76.github.io/neural-networks/object-detection/losses-for-segmentation/)

Also having [Focal Loss](https://lars76.github.io/neural-networks/object-detection/losses-for-segmentation/) would be useful.

**Comment by RParedesPalacios** [comment]
Hi, i guess you mean Dice **metric**, don't you? 

I will implement now as a new metric. In any case, this metric requiere discrete activations in the tensors. The simplest case will be binary, in any case we need to binarize, are you aware of that?

I mean that you should provide some threshold in some point. Right now i will put 0.5.

An I wrong?

**Comment by RParedesPalacios** [comment]
Well, it is implemented, bye!
