### ISSUE TITLE
eddlT commented out

### ISSUE THREAD

**Issue by CostantinoGrana** [deephealthproject/eddl#157]
The disappearance of eddlT.h killed all programs using it. Such change should be preceded by a deprecation notice some times before. And should be justified by important reasons.

An example are the pipelines to be used in the next week Hackathon, which now don't compile anymore.

We will fix the code, but it's not the correct workflow.

**Comment by RParedesPalacios** [comment]
I agree... Salva is always quite optimistic

**Comment by CostantinoGrana** [comment]
No problem, we already fixed it for pneumothorax. We will fix also skin_lesion pipelines and update.
