### ISSUE TITLE
Dilated Convolution

### ISSUE THREAD

**Issue by lauracanalini** [deephealthproject/eddl#171]
We were trying to use dilated convolution through the `dilation_rate` parameter of the `Conv` Layer. We noticed however that the parameter is never passed to the constructor of the `ConvolDescriptor` and therefore its value is lost and never used. 

https://github.com/deephealthproject/eddl/blob/f2f1391a5339d7962b3ec4ea8cd9da0e546b2223/src/layers/conv/layer_conv.cpp#L27-L30

**Comment by salvacarrion** [comment]
It is not yet implemented. It is there as a sort of a contract.
