### ISSUE TITLE
Missing destructors

### ISSUE THREAD

**Issue by lauracanalini** [deephealthproject/eddl#172]
We noticed that the destructors of several classes are missing (e.g., `ConvolDescriptor`, `PoolDescriptor`, `LConv` and `LBatchNorm` but also others) and this causes large memory leaks. Can you check it out?

**Comment by salvacarrion** [comment]
I'll check out. Keep in mind that there are many memory leaks as we've been focus on other things (installation, dependency management, correctness, etc)
