### ISSUE TITLE
Error: unlock of unowned mutex

### ISSUE THREAD

**Issue by MicheleCancilla** [deephealthproject/eddl#197]
I'm trying to execute the pipeline with Visual Studio 2017, but the application crashes with `unlock of unowned mutex` error.

The crash occurs in Tensor destructor when trying to unlock an already unlocked mutex:
https://github.com/deephealthproject/eddl/blob/6a84eb9358c077a76ebe0a9bab99c452367e5259/src/tensor/tensor.cpp#L111

The [mutex::unlock()](https://en.cppreference.com/w/cpp/thread/mutex/unlock) reference says:
> The mutex must be locked by the current thread of execution, otherwise, the behavior is undefined.

I think you could use `std::unique_lock` and `std::lock_guard` to manage semaphore for Tensor.
I don't know if this error also happens with other compilers.

**Comment by RParedesPalacios** [comment]
Hi, yes this is related to the delete problems as well we are going to check that

**Comment by salvacarrion** [comment]
Fixed. #219
