### ISSUE TITLE
Segmentation fault when deleting a GPU net

### ISSUE THREAD

**Issue by simleo** [deephealthproject/eddl#200]
As of EDDL 0.7.0, deleting a net built with a `CS_GPU` causes a segmentation fault:

```cpp
#include <eddl/apis/eddl.h>

using namespace eddl;

int main(int argc, char **argv) {
    layer in = Input({784});
    layer l = in;
    l = Activation(Dense(l, 256), "relu");
    layer out = Dense(l, 784);
    model net = Model({in}, {out});
    build(net,
          sgd(0.001, 0.9),
          {"mean_squared_error"},
          {"mean_squared_error"},
          CS_GPU({1})
    );
    delete net;
}
```

The impact on the Python bindings is to break any program that tries to use the GPU, since all objects are automatically deleted by the interpreter at shutdown. This problem was not present in EDDL 0.6.0.

Note that the segmentation fault does not happen if a `CS_CPU` is used instead.

**Comment by RParedesPalacios** [comment]
Hi, yes we are on the way to check these deletes.

**Comment by RParedesPalacios** [comment]
Please check new master Release.

**Comment by simleo** [comment]
> Please check new master. If everything works it will be 0.7.1

With pyeddl at [this revision](https://github.com/simleo/pyeddl/tree/191dedbdd495b351abe6f8e07c94864dec01097b) (in my fork), on top of EDDL rev. [4f6d6de6](https://github.com/deephealthproject/eddl/tree/4f6d6de685e0e76f51b451624829489d176e9964), all current Python tests and examples run fine. Please go ahead with tag 0.7.1.

**Comment by simleo** [comment]
Also looks OK with the [latest master](https://github.com/deephealthproject/eddl/tree/8c9878af32e8fc363cbeffaa9c845995a2019e68)
