### ISSUE TITLE
Dots printed calling forward function

### ISSUE THREAD

**Issue by giobus75** [deephealthproject/eddl#220]
Hi, 
using the forward function during the evaluation, I got several dots as video output. Dots are printed after some batches are processed (in my application every 205 batches). 

Digging a bit in the code I found out that it is probably due to the function ```void Tensor::select(Tensor *A, Tensor *B, vector<int> sind, int ini, int end, bool mask_zeros)```. Maybe the ``` cout<<".....";``` at row 794 could be the issue.

I did not have this problem with the tagged version 0.7.1.

Thank you.

**Comment by salvacarrion** [comment]
I not sure if I have understood the problem. Can you elaborate on it a bit more? 
Btw, the last release is v0.8a.

**Comment by giobus75** [comment]
Hi, I mean that the cout at row 794 in https://github.com/deephealthproject/eddl/blob/v0.8a/src/tensor/tensor_core.cpp (and not present in the v0.7.1) is probably causing some unwanted print of dots at the screen. Specifically, this happens during the evaluation step as I call the forward function (row 188 in the code of my application https://github.com/deephealthproject/promort_pipeline/blob/master/python/promort_cassandra.py)
In the attached image, the output of my program:
![image](https://user-images.githubusercontent.com/46683396/100801622-89ca3a00-3428-11eb-9ad1-a4dc501bc8a8.png)

By the way, you can get a similar behavior running the example mnist_loss (or mnist_rnn_func.cpp or mnist_mlp_func.cpp). This is a sample of mnist_loss output:
![image](https://user-images.githubusercontent.com/46683396/100803599-b895df80-342b-11eb-9b1f-6a92e9cbb727.png)

You don't get the same behavior by using the other mnist examples that do not call the forward function.
This issue is present both using the cpu and the gpu.
I hope it is useful :-).
Giovanni

**Comment by salvacarrion** [comment]
okay, understood. We'll try to use the same printing as in the other examples.

**Comment by RParedesPalacios** [comment]
Ok new Release we will remove this dots
