### ISSUE TITLE
Problems with multi-GPU

### ISSUE THREAD

**Issue by salvacarrion** [deephealthproject/eddl#222]
**Describe the bug**
Only one GPU is used when a model is run in multi-gpu mode

**To Reproduce**
1. Use `CS_GPU({1,1})`
2. Check with `nvidia-smi`

**Expected behavior**
Use of selected GPUs

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 16.04

**Hint**
Could be related to this line:
https://github.com/deephealthproject/eddl/blob/f754672fe491322acb8c4b18393743baa8129459/src/net/net_api.cpp#L159

**Comment by RParedesPalacios** [comment]
I think this is solved now in Master in the new release. We remove the mop taskloop and use the standard amp parallel for
