### ISSUE TITLE
Strange loss behavior

### ISSUE THREAD

**Issue by giobus75** [deephealthproject/eddl#225]
Hi, I'm using the pyeddl bindings (eddl v0.8a) with GPU and I'm experiencing a strange behavior of the loss function.
Starting my classification application (https://github.com/deephealthproject/promort_pipeline/blob/master/python/promort_cassandra.py) I suddenly get a very low value for the loss function (with respect to the usual one I got with the previous eddl versions). I don't know if it can be useful but after investigating a bit, I found out that the behavior changes with the batch size (bs). It seems that by increasing the bs, the loss function scales down with about the same factor. As an example, in the following figures, the output after about 200 iterations (epoch 0) for bs=1, 2, 4, 8, 16

![bs1](https://user-images.githubusercontent.com/46683396/101208055-e66c6580-3671-11eb-9426-e41b2bff4ad1.png)

![bs2](https://user-images.githubusercontent.com/46683396/101208216-19165e00-3672-11eb-8ecb-fe36e4ecf028.png)

![bs4](https://user-images.githubusercontent.com/46683396/101208072-eb311980-3671-11eb-9244-6d871606d3f6.png)

![bs8](https://user-images.githubusercontent.com/46683396/101208229-20d60280-3672-11eb-8665-be428f2959a2.png)

![bs16](https://user-images.githubusercontent.com/46683396/101208086-ee2c0a00-3671-11eb-83b5-87c430d2bc1e.png)

Using the v0.7.1 I got a loss function value of about 1.5 after the same number of iterations and it is not so sensitive to the batch size.

I tried also a C++ eddl example (mnist_conv) by using both eddl v0.7.1 and v0.8a and I found out that the output of the program is very different:

here the output of v0.7.1:
![mnist_conv_v0 7 1](https://user-images.githubusercontent.com/46683396/101208548-a2c62b80-3672-11eb-950d-c129ed06bfcc.png)
 
this one with the v0.8a:
![mnist_conv_v0 8a](https://user-images.githubusercontent.com/46683396/101208597-b07bb100-3672-11eb-9d1f-50d9b2b385a8.png)

As you can see, in the v0.8a at the end of the first epoch the loss function shows a very small value and turns to a nan value at the end of the computation with a collapse of the accuracy.

In this case, I did not make experiments changing the batch size and I always used the GPU only.
Hope it can help.
Giovanni

**Comment by salvacarrion** [comment]
Fixed #228
