### ISSUE TITLE
Segmentation faults when deleting net

### ISSUE THREAD

**Issue by simleo** [deephealthproject/eddl#241]
In the develop branch, as of 280795c942e5dd5a62d79a2968bbac84a5d2f2c4, some examples crash with a segmentation fault when the net is deleted after training/validation. To reproduce, just add a `delete net;` at the end of the `mnist_rnn` example, as the last instruction in `main`. According to my checks, this problem is exposed by the following examples:

* `mnist_rnn`
* `mnist_losses`
* `nlp_sentiment_rnn`
* `drive_seg`

**Comment by RParedesPalacios** [comment]
Yes we detected that. Now is solved in the last develop push. Anyway i am running that examples.
