### ISSUE TITLE
`get_fmem()` issues

### ISSUE THREAD

**Issue by MicheleCancilla** [deephealthproject/eddl#244]
I was looking for windows incompatibilites in develop branch and I spotted some issues regarding the `get_fmem()` function that could be solved.

-
  ```
  unsigned long freemem = get_free_mem();
  ```
  The `get_free_mem()` function returns an `unsigned long` which could cause [integer overflow](https://en.cppreference.com/w/cpp/language/types). I would move return type to `unsigned long long`.
- 
  ```
  try{
      //ptr = new float[size];
      //ptr=(float *)malloc(size*sizeof(float));
      //ptr=(float *)aligned_alloc(64, size*sizeof(float));
      posix_memalign((void **)&ptr, 64, size*sizeof(float));
  }
  catch (std::bad_alloc& badAlloc){
      error=true;
  }
  ```
  `posix_memalign()` is not available on windows. `_aligned_malloc()` could be a windows replacement but requires a specific function for freeing memory (`_aligned_free()`) instead of `free()`. Two feasible choices are:
  1. Define `eddl_malloc()` and `eddl_free()` which contain call to posix_memalign/_aligned_malloc (and free/_aligned_free).
  2. Use `malloc()` under windows loosing the _alignment_ feature.
  
  The try/catch is now useless since `posix_memalign()` does not throw any exceptions, but it [returns an error code](https://man7.org/linux/man-pages/man3/posix_memalign.3.html).

I can open a PR so you can test the changes.

**Comment by jonandergomez** [comment]
Thanks Michele, I'm going to solve it asap.

**Comment by jonandergomez** [comment]
Dear Michele, 

I just pushed a commit into develop facing what you commented, but I have no the chance to test it in Windows, could you check it?
I'm ready to fix any bug derived from this commit.

Regads,

Jon

**Comment by MicheleCancilla** [comment]
Dear Jon,
the tests do not pass on windows, but I understand why. The `TensorTestSuite.tensor_math_unary_log` test fails throwing exception in `eddl_malloc`.
I have verified that `errno != 0` is true before calling _aligned_malloc and errno value is 33 (EDOM Math argument).
```
auto err_ = errno;
ptr = _aligned_malloc(size, alignment_block_size);
error = (nullptr == ptr || errno != 0);
err_ = errno;
```

I suggest only checking if allocation fails ([doc](https://docs.microsoft.com/it-it/cpp/c-runtime-library/reference/aligned-malloc)):
```
ptr = _aligned_malloc(size, alignment_block_size);
error = (nullptr == ptr || errno == ENOMEM);
```
<br><br>

I get a different compilation error (`a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax`) on [_5_nlp_text_generation_](https://github.com/deephealthproject/eddl/blob/de7a59e68e95d0c371d0eb04200a11fb87536bfe/examples/nn/4_NLP/5_nlp_text_generation.cpp#L265). You should remove parentheses around `vtensor`:
```
forward(decoder, vtensor{ word,treshape,state });
```

**Comment by CostantinoGrana** [comment]
For everybody: `errno` should be set to 0 before calling a function, if you plan to check its value. `errno` should be checked only in case of error in function.
Check this: https://softwareengineering.stackexchange.com/a/209731/360023

**Comment by jonandergomez** [comment]
Thanks for the comment Costantino. And thanks for the suggestion Michele.

Let me solve it and I will push a commit.

Jon

**Comment by jonandergomez** [comment]
Hi again,

Commit following your indications pushed, also the compiling problem with the call to forward in the NLP example fixed. 

Michele, could you please check in windows if both problems are solved?

Regards,

Jon

**Comment by MicheleCancilla** [comment]
No, it does not work 😂
There is an [error in the _errno_ condition](https://github.com/deephealthproject/eddl/blob/d34abb25181c7fa138e3619e64b59b76e693d867/src/utils.cpp#L113) `error = (nullptr == ptr || errno != ENOMEM);`.
It should be `error = (nullptr == ptr || errno == ENOMEM);`.

**Comment by jonandergomez** [comment]
Sorry, my logic fails. I need a windows instance to do checks and avoid bothering you with this.
Please, check it after the last commit and close the issue if finally it runs.
Regards,
Jon

**Comment by MicheleCancilla** [comment]
Yes, it works! Thank you Jon.
