### ISSUE TITLE
onnx import clarification

### ISSUE THREAD

**Issue by MicheleCancilla** [deephealthproject/eddl#257]
The last eddl release provides an example (8_cifar_pretrained.cpp) that:
 - imports a net from ONNX
 - deletes the last `dense` layer
 - adds a new `dense` by means of networks merging

However, the lines:
https://github.com/deephealthproject/eddl/blob/690f3b6cd8b6287247e850204de0c7a4911486a1/examples/onnx/nn/2_cifar10/8_cifar_pretrained.cpp#L51-L58
do not contain the `init_weights = false` flag that avoids the random weight initialization.

Is the `false` flag required in this case?

**Comment by RParedesPalacios** [comment]
Yes, but then we will not initialize the new layers... so i have to think how to fix that.
