### ISSUE TITLE
removeLayer() causes vector subscript out of range error

### ISSUE THREAD

**Issue by MicheleCancilla** [deephealthproject/eddl#258]
**Describe the bug**
Removing the last layer of Net causes vector subscript out of range debug assertion error in debug on Visual Studio.
The error occurs on net_build.cpp:
https://github.com/deephealthproject/eddl/blob/6759e7976f045e3cd10e43a3f23a9be8e4880562/src/net/net_build.cpp#L61

The last layer apparently has empty child vector, so `layers[j]->child[0]` causes out of range error.

**To Reproduce**
1. Run `onnx_export` to create the "trained_model.onnx" file
2. Edit the file `3_onnx_import_net_from_file.cpp` adding the removeLayer of last _softmax_:
    ```cpp
    Net* net = import_net_from_onnx_file(path, DEV_CPU);
    removeLayer(net, "softmax6");
    // Build model
    build(net,
          rmsprop(0.01), // Optimizer
          {"softmax_cross_entropy"}, // Losses
          {"categorical_accuracy"}, // Metrics
          CS_GPU({1}, "low_mem"), // one GPU
          //CS_CPU(), // CPU with maximum threads availables
          false
    );
    ```
3. Debug the example `onnx_import`

**Comment by RParedesPalacios** [comment]
Here it is important to decide which layers are going to be the output of the network. If you remove the softmax but still pretend to build it with some loss and metrics associated... it has non sense

**Comment by RParedesPalacios** [comment]
Let me work on this and i will provide a way of doing

**Comment by RParedesPalacios** [comment]
Check 3_onnx_import_net_from_file.cpp in develop branch
