### ISSUE TITLE
Addition of padding layer

### ISSUE THREAD

**Issue by georgemavrakis-wings** [deephealthproject/eddl#270]
Good morning,

**Problem description.**
The problem that I am facing is that I cannot find a way to custom pad the output of an intermediate layer, in order to use it as input in an Conv1D layer with padding option equal with 'none'. 
For example, I want to pass an input from a Conv1D layer with kernel size = 8. As far as I know, the padding = same option pads the input (1D case) by adding 3 zero columns to the left of the sample and 4 zero columns to the right. However, I want to pad the input in order to have 4 zero columns to the left and 3 zero columns to the right.

**Describe the feature**
A pad layer which would take a layer as an input and would pad it along the user specified dimension with constant values or reflection of the borders for [x columns left, y columns right] (1D input) or [x columns left, y columns right], [z columns above, r columns below] (2D input)

**Comment by salvacarrion** [comment]
We'll try to added asap

**Comment by salvacarrion** [comment]
Update: We're currently working on this feature

**Comment by salvacarrion** [comment]
Available in develop
