### ISSUE TITLE
Issue with ConvT2D

### ISSUE THREAD

**Issue by ipediez** [deephealthproject/eddl#275]
Good morning, 

I have encountered an issue when using ConvT2D(). We built the network originally with keras and now are performing the conversion to EDDL code through python. We initially substituted the ConvT2D layers for UpSampling ones, to asses if the full code was working, and we were able to make the training work. Nevertheless, when using the ConvT2D() function the execution breaks. 

For EDDL, the parameter output_padding is mandatory, but not for keras nor pytorch. After reading the documentation of those libraries, we have computed for our data a padding = "same" and output_padding = [1,1]. Nevertheless, the execution still breaks. 

We have then realized that in the online [EDDL documentation](https://deephealthproject.github.io/eddl/layers/convolutional.html#convolutional-transpose) that ConvT2D is "not yet implemented". Are you currently working on this feature? Do you expect it to be available during the next months?

In case the ConvT2D was already available, could you provide a hint on how to compute the output_padding for EDDL, in case it differs from pytorch?

Thank you

**Comment by RParedesPalacios** [comment]
ConvT2D is in our plans, but surely only with CudNN, but not for cpu or Cuda.

**Comment by ipediez** [comment]
Hi Roberto, 

¿Are the metrics accuracy and categorical_accuracy available? I am trying to use both aliases and keep getting the following error, while other metrics like mse seem to work:

RuntimeError: RuntimeError: Tensor::Accuracy

**Comment by salvacarrion** [comment]
Update: We're currently working on this feature

**Comment by salvacarrion** [comment]
Fixed.
