### ISSUE TITLE
Cannot build shared library

### ISSUE THREAD

**Issue by simleo** [deephealthproject/eddl#68]
Shared library build (i.e., with `-D EDDL_SHARED=ON` passed to cmake) fails with:

```
[...]
[ 73%] Linking CXX shared library libeddl.so
CMakeFiles/eddl.dir/src/helpers.cpp.o: In function `get_next_row(std::istream&, CSVRow&, char const&)':
helpers.cpp:(.text+0x0): multiple definition of `get_next_row(std::istream&, CSVRow&, char const&)'
CMakeFiles/eddl.dir/src/tensor/tensor_serialization.cpp.o:tensor_serialization.cpp:(.text+0x3eba0): first defined here
collect2: error: ld returned 1 exit status
CMakeFiles/eddl.dir/build.make:2351: recipe for target 'libeddl.so' failed
make[2]: *** [libeddl.so] Error 1
CMakeFiles/Makefile2:442: recipe for target 'CMakeFiles/eddl.dir/all' failed
make[1]: *** [CMakeFiles/eddl.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

The problem seems to be that `helpers.h` contains the full definition (rather than just the declaration) of `get_next_row`. In this case include guards do not help, and the file is included by two different `.cpp` files. I was able to build the shared library by simply adding `static` to the definition:

```diff
diff --git a/src/helpers.h b/src/helpers.h
index e3b983f..6f37f6d 100644
--- a/src/helpers.h
+++ b/src/helpers.h
@@ -45,7 +45,7 @@ private:
     std::vector<std::string>    m_data;
 };
 
-std::istream& get_next_row(std::istream& str, CSVRow& data, const char &delimiter)
+static std::istream& get_next_row(std::istream& str, CSVRow& data, const char &delimiter)
 {
     data.readNextRow(str, delimiter);
     return str;
```

This could be a viable solution if `get_next_row` is meant to be used only by `CSVIterator`.

**NOTE: this affects EDDL 0.3.**

**Comment by ynsehoornenborg** [comment]
Although the static definition fixes the compile issue. However, as its only used once, shouldn't we remove the method and place the code inline?

Anyway, is might make sense to add a helpers.cpp file, and place the implementation there. This is done with almost all the others.
