### ISSUE TITLE
eddlT::save fails if the path has no directory component

### ISSUE THREAD

**Issue by simleo** [deephealthproject/eddl#69]
This worked in EDDL 0.2.2:

```cpp
eddlT::save(t, "foo.bin", "bin");
```

But now it fails with:

```
The file could not be saved. Check if the directory exists or if you have permissions to write in it. (Tensor::save)
```

This is due to a problem with the newly introduced check for directory existence in `Tensor::save`, which does not handle the case of implicit CWD. Now the user is forced to do this in order to save to the CWD:

```cpp
eddlT::save(t, "./foo.bin", "bin");
```

The `mnist_[w]gan` examples are currently broken due to this.

**Comment by salvacarrion** [comment]
This week it will be fixed. 
By the way, there is no need to include the format "bin". It is inferred from the name so you can write:` t->save("output.jpg"), t->save("output.npy"), t->save("output.bin"),...`
