### ISSUE TITLE
Automatically push the documentation to the cloud

### ISSUE THREAD

**Issue by salvacarrion** [deephealthproject/eddl#92]
Right now, I have to copy-paste the sphinx documentation I build locally, to a GitHub repo so that it can be online though Github Pages: [https://github.com/deephealthproject/eddl](https://github.com/deephealthproject/eddl)

Since this can be easily automated through Jenkins (...or ReadTheDocs), I think we should add a few lines to our Jenkins file to make it work (like we did with doxygen). I prefer ReadTheDocs but I'm not sure if it can deal with C++ stuff.

Our sphinx documentation is augmented with `Doxygen` through `Breathe`, so you need to build both:
```
cd docs/doxygen
doxygen

cd docs/source
make html
```

**Comment by prittt** [comment]
Ok, it will be very easy to automate the process with Jenkins. Would you prefer to have a separate repo for the doc or a branch on the eddl one as we did for ecvl? Take a look <a href="https://github.com/deephealthproject/ecvl/tree/gh-pages">here</a>.

**Comment by prittt** [comment]
The idea is to have an index page that points to both master documentation and specific release documentation (automatically generated), eventually using different "styles" like doxygen, sphinx etc. Something similar to what OpenCV do (https://docs.opencv.org).

**Comment by salvacarrion** [comment]
I fixed it today, so I'm closing this issue. The docs are build using Github Actions and then pushed to gh-pages.
[https://deephealthproject.github.io/eddl/](https://deephealthproject.github.io/eddl/)
